### PR TITLE
Add run_unique_key to .global files in simulation

### PR DESCRIPTION
**Pull request by pmandrik**
Add dummy run_unique_key to the created .global files at the moment.

**WIP:**
- extract run_unique_key from the original run used for the simulation? check how this key is important in the cmsRun

### CODE REVIEW

**Comment by jfernan2** [comment]
I believe we can merge this after the succesful test, @pmandrik

**Comment by pmandrik** [comment]
@jfernan2 would it make sense to add run_unique_key to the simulator.conf [0] so it will be possible to change this variable later without intervention into code?

[0] https://github.com/cms-DQM/fff_dqmtools/blob/FFF_DQMTOOLS_V1/misc/fff_simulator_dqmtools.conf

**Comment by jfernan2** [comment]
Yes, afaiu it makes sense, we already have run_key too

**Comment by pmandrik** [comment]
Hi, @jfernan2 ,
propagation of the run_unique_key from cfg file is added. Tested to work at P5. Ready to merge I think.

**Comment by jfernan2** [comment]
Thanks @pmandrik

**Pull request merged**
